"""Add composite unique constraint and update columns

Revision ID: 493a1fc39a89
Revises: f4f077e4e19a
Create Date: 2025-08-08 18:26:48.887036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493a1fc39a89'
down_revision: Union[str, Sequence[str], None] = 'f4f077e4e19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_entries_description'), table_name='tracker_entries')
    op.create_unique_constraint('_owner_id_title_uc', 'tracker_entries', ['owner_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_owner_id_title_uc', 'tracker_entries', type_='unique')
    op.create_index(op.f('ix_tracker_entries_description'), 'tracker_entries', ['description'], unique=False)
    # ### end Alembic commands ###
