"""Create tracker_entries table

Revision ID: eba3f1700054
Revises: 6e3497ad966b
Create Date: 2025-08-07 00:05:08.969395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba3f1700054'
down_revision: Union[str, Sequence[str], None] = '6e3497ad966b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_enrites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_enrites_description'), 'tracker_enrites', ['description'], unique=False)
    op.create_index(op.f('ix_tracker_enrites_title'), 'tracker_enrites', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_enrites_title'), table_name='tracker_enrites')
    op.drop_index(op.f('ix_tracker_enrites_description'), table_name='tracker_enrites')
    op.drop_table('tracker_enrites')
    # ### end Alembic commands ###
