"""Create tracker_entries table

Revision ID: f4f077e4e19a
Revises: 99734e3f7a6a
Create Date: 2025-08-07 01:26:02.876294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f077e4e19a'
down_revision: Union[str, Sequence[str], None] = '99734e3f7a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_entries_description'), 'tracker_entries', ['description'], unique=False)
    op.create_index(op.f('ix_tracker_entries_title'), 'tracker_entries', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_entries_title'), table_name='tracker_entries')
    op.drop_index(op.f('ix_tracker_entries_description'), table_name='tracker_entries')
    op.drop_table('tracker_entries')
    # ### end Alembic commands ###
